# Generated by Django 5.1.3 on 2024-11-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0006_chainlink_delete_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chainlink",
            name="contacts",
            field=models.ManyToManyField(
                blank=True, to="retail.contact", verbose_name="Контакты"
            ),
        ),
        migrations.AlterField(
            model_name="chainlink",
            name="products",
            field=models.ManyToManyField(
                blank=True, to="retail.product", verbose_name="Продукты"
            ),
        ),
    ]
